/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package app.view;

import app.controller.MainController;
import java.awt.Color;
import java.awt.Component;
import java.awt.Container;
import java.util.ArrayList;
import javax.swing.JTextField;
import javax.swing.border.LineBorder;

/**
 *
 * @author lazon
 */
public class MainView extends javax.swing.JFrame {

    ArrayList<JTextField> myFields = new ArrayList<>();

    /**
     * Creates new form mainView
     */
    public MainView() {
        initComponents();
        panel_AddProduct.setVisible(false);
        panel_ListProducts.setVisible(false);
        panel_RemoveProduct.setVisible(false);
        panel_UpdatePrice.setVisible(false);
        panel_ListProductRange.setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        contenedor = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        btn_PanelAddProduct = new javax.swing.JButton();
        btn_PanelRemoveProduct = new javax.swing.JButton();
        btn_PanelUpdateProduct = new javax.swing.JButton();
        btn_PanelListProducts = new javax.swing.JButton();
        btn_PanelListRange = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        panel_ListProductRange = new javax.swing.JPanel();
        jScrollPane4 = new javax.swing.JScrollPane();
        myListTableRange = new javax.swing.JTable();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        ftf_minPrice = new javax.swing.JFormattedTextField();
        ftf_maxPrice = new javax.swing.JFormattedTextField();
        btn_updateTable = new javax.swing.JButton();
        panel_ListProducts = new javax.swing.JPanel();
        jScrollPane3 = new javax.swing.JScrollPane();
        myListTable = new javax.swing.JTable();
        panel_AddProduct = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        tf_name = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        cb_Category = new javax.swing.JComboBox<>();
        jLabel4 = new javax.swing.JLabel();
        lb_statusAdd = new javax.swing.JLabel();
        btn_ActionAddProduct = new javax.swing.JButton();
        ftf_priceAdd = new javax.swing.JFormattedTextField();
        panel_UpdatePrice = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        tf_nameUpdate = new javax.swing.JTextField();
        btn_ActionUpdateProduct = new javax.swing.JButton();
        lb_updateConfirmed = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        ftf_priceUpdate = new javax.swing.JFormattedTextField();
        panel_RemoveProduct = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        tf_nameRemove = new javax.swing.JTextField();
        btn_ActionRemoveProduct = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        lb_deleteConfirmed = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Gestor de productos");
        setMinimumSize(new java.awt.Dimension(780, 562));
        setResizable(false);

        jPanel1.setLayout(new java.awt.GridLayout(6, 1, 0, 15));

        btn_PanelAddProduct.setText("Add product");
        btn_PanelAddProduct.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_PanelAddProductActionPerformed(evt);
            }
        });
        jPanel1.add(btn_PanelAddProduct);

        btn_PanelRemoveProduct.setText("Remove product");
        btn_PanelRemoveProduct.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_PanelRemoveProductActionPerformed(evt);
            }
        });
        jPanel1.add(btn_PanelRemoveProduct);

        btn_PanelUpdateProduct.setText("Update price");
        btn_PanelUpdateProduct.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_PanelUpdateProductActionPerformed(evt);
            }
        });
        jPanel1.add(btn_PanelUpdateProduct);

        btn_PanelListProducts.setText("List all products");
        btn_PanelListProducts.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_PanelListProductsActionPerformed(evt);
            }
        });
        jPanel1.add(btn_PanelListProducts);

        btn_PanelListRange.setText("List products in range");
        btn_PanelListRange.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_PanelListRangeActionPerformed(evt);
            }
        });
        jPanel1.add(btn_PanelListRange);

        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        panel_ListProductRange.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        myListTableRange.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane4.setViewportView(myListTableRange);

        panel_ListProductRange.add(jScrollPane4, new org.netbeans.lib.awtextra.AbsoluteConstraints(157, 0, 390, -1));

        jLabel9.setText("Min. price");
        panel_ListProductRange.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, -1, -1));

        jLabel10.setText("Max. price");
        panel_ListProductRange.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 80, -1, -1));

        ftf_minPrice.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("#0.00"))));
        panel_ListProductRange.add(ftf_minPrice, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 30, 120, -1));

        ftf_maxPrice.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("#0.00"))));
        panel_ListProductRange.add(ftf_maxPrice, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 100, 120, -1));

        btn_updateTable.setText("Update table");
        btn_updateTable.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_updateTableActionPerformed(evt);
            }
        });
        panel_ListProductRange.add(btn_updateTable, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 170, -1, -1));

        jPanel2.add(panel_ListProductRange, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 547, -1));

        panel_ListProducts.setLayout(new java.awt.BorderLayout());

        myListTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane3.setViewportView(myListTable);

        panel_ListProducts.add(jScrollPane3, java.awt.BorderLayout.CENTER);

        jPanel2.add(panel_ListProducts, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 547, -1));

        panel_AddProduct.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setText("Name:");
        panel_AddProduct.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 40, 50, 30));
        panel_AddProduct.add(tf_name, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 40, 180, 30));

        jLabel3.setText("Price:");
        panel_AddProduct.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 86, 50, 30));

        cb_Category.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Computing", "Cables", "Accesories", "Components", "Electronics" }));
        panel_AddProduct.add(cb_Category, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 160, 180, 30));

        jLabel4.setText("Category");
        panel_AddProduct.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 160, -1, 30));

        lb_statusAdd.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        panel_AddProduct.add(lb_statusAdd, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 230, 470, 70));

        btn_ActionAddProduct.setText("Add product");
        btn_ActionAddProduct.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_ActionAddProductActionPerformed(evt);
            }
        });
        panel_AddProduct.add(btn_ActionAddProduct, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 370, -1, -1));

        ftf_priceAdd.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("#0.00"))));
        panel_AddProduct.add(ftf_priceAdd, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 90, 180, 30));

        jPanel2.add(panel_AddProduct, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 547, 420));

        panel_UpdatePrice.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel8.setText("Name:");
        panel_UpdatePrice.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 150, 50, 30));
        panel_UpdatePrice.add(tf_nameUpdate, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 150, 340, 30));

        btn_ActionUpdateProduct.setText("Update");
        btn_ActionUpdateProduct.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_ActionUpdateProductActionPerformed(evt);
            }
        });
        panel_UpdatePrice.add(btn_ActionUpdateProduct, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 370, -1, -1));

        lb_updateConfirmed.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        panel_UpdatePrice.add(lb_updateConfirmed, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 70, 320, 30));

        jLabel11.setText("Price:");
        panel_UpdatePrice.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 210, 50, 30));

        ftf_priceUpdate.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("#0.00"))));
        panel_UpdatePrice.add(ftf_priceUpdate, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 210, 340, 30));

        jPanel2.add(panel_UpdatePrice, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 547, 420));

        panel_RemoveProduct.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel5.setText("Name:");
        panel_RemoveProduct.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 160, 50, 30));
        panel_RemoveProduct.add(tf_nameRemove, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 160, 340, 30));

        btn_ActionRemoveProduct.setText("Remove");
        btn_ActionRemoveProduct.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_ActionRemoveProductActionPerformed(evt);
            }
        });
        panel_RemoveProduct.add(btn_ActionRemoveProduct, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 370, -1, -1));

        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel6.setText("This action cannot be undone! Make sure you are certain ");
        panel_RemoveProduct.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 40, 400, 50));

        jLabel7.setText("before pulling the trigger!");
        panel_RemoveProduct.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 80, -1, -1));

        lb_deleteConfirmed.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        panel_RemoveProduct.add(lb_deleteConfirmed, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 200, 320, 30));

        jPanel2.add(panel_RemoveProduct, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 547, 420));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 3, 36)); // NOI18N
        jLabel1.setText("Casandra's warehouse system");

        javax.swing.GroupLayout contenedorLayout = new javax.swing.GroupLayout(contenedor);
        contenedor.setLayout(contenedorLayout);
        contenedorLayout.setHorizontalGroup(
            contenedorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(contenedorLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(contenedorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(contenedorLayout.createSequentialGroup()
                        .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 191, Short.MAX_VALUE)
                        .addGap(18, 18, 18)
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 547, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(contenedorLayout.createSequentialGroup()
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 540, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        contenedorLayout.setVerticalGroup(
            contenedorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, contenedorLayout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 45, Short.MAX_VALUE)
                .addGroup(contenedorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(contenedor, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(contenedor, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_PanelAddProductActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_PanelAddProductActionPerformed
        // TODO add your handling code here:
        panel_AddProduct.setVisible(true);
        panel_ListProducts.setVisible(false);
        panel_RemoveProduct.setVisible(false);
        panel_UpdatePrice.setVisible(false);
        panel_ListProductRange.setVisible(false);
        gatherTF(panel_AddProduct);
    }//GEN-LAST:event_btn_PanelAddProductActionPerformed

    private void btn_ActionAddProductActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_ActionAddProductActionPerformed
        // TODO add your handling code here:
        if (checkStatus() || tf_name.getText().length()<3) {
            
            String aux = ftf_priceAdd.getText().replace(",", ".");
            
            if (MainController.insertProduct(tf_name.getText(), Float.parseFloat(aux), cb_Category.getSelectedIndex() + 1)) {
                lb_statusAdd.setForeground(Color.green);
                lb_statusAdd.setText("Product added successfully!");
            } else {
                lb_statusAdd.setForeground(Color.red);
                lb_statusAdd.setText("I'm sorry, the product could not be added. Check everything it's okay and try again.");
            }
        }else{
            lb_statusAdd.setForeground(Color.red);
            lb_statusAdd.setText("Make sure to fill everything!");
        }

    }//GEN-LAST:event_btn_ActionAddProductActionPerformed

    private void btn_ActionRemoveProductActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_ActionRemoveProductActionPerformed
        if (checkStatus()) {
            if (MainController.removeProducts(tf_nameRemove.getText())) {
                lb_deleteConfirmed.setForeground(Color.green);
                lb_deleteConfirmed.setText("Product removed successfully!");
            } else {
                lb_deleteConfirmed.setForeground(Color.red);
                lb_deleteConfirmed.setText("I'm sorry, the product could not be removed. Check everything it's okay and try again.");
            }
        }else{
            lb_statusAdd.setForeground(Color.red);
            lb_statusAdd.setText("Make sure to fill everything!");
        }
    }//GEN-LAST:event_btn_ActionRemoveProductActionPerformed

    private void btn_PanelRemoveProductActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_PanelRemoveProductActionPerformed
        panel_AddProduct.setVisible(false);
        panel_ListProducts.setVisible(false);
        panel_RemoveProduct.setVisible(true);
        panel_UpdatePrice.setVisible(false);
        panel_ListProductRange.setVisible(false);
        gatherTF(panel_RemoveProduct);
    }//GEN-LAST:event_btn_PanelRemoveProductActionPerformed

    private void btn_ActionUpdateProductActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_ActionUpdateProductActionPerformed
        if (checkStatus() || tf_nameUpdate.getText().length()<3) {
            
            String aux = ftf_priceUpdate.getText().replace(",", ".");
            
            if (MainController.updatePrice(tf_nameUpdate.getText(), Float.parseFloat(aux))) {
                lb_updateConfirmed.setForeground(Color.green);
                lb_updateConfirmed.setText("Product updated successfully!");
            } else {
                lb_updateConfirmed.setForeground(Color.red);
                lb_updateConfirmed.setText("I'm sorry, the product could not be updated. Check everything it's okay and try again.");
            }
        }else{
            lb_updateConfirmed.setForeground(Color.red);
            lb_updateConfirmed.setText("Make sure to fill everything!");
        }
    }//GEN-LAST:event_btn_ActionUpdateProductActionPerformed

    private void btn_PanelUpdateProductActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_PanelUpdateProductActionPerformed
        panel_AddProduct.setVisible(false);
        panel_ListProducts.setVisible(false);
        panel_RemoveProduct.setVisible(false);
        panel_UpdatePrice.setVisible(true);
        panel_ListProductRange.setVisible(false);
        gatherTF(panel_UpdatePrice);
    }//GEN-LAST:event_btn_PanelUpdateProductActionPerformed

    private void btn_PanelListProductsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_PanelListProductsActionPerformed
        panel_AddProduct.setVisible(false);
        panel_ListProducts.setVisible(true);
        panel_RemoveProduct.setVisible(false);
        panel_UpdatePrice.setVisible(false);
        panel_ListProductRange.setVisible(false);
        myListTable.setModel(MainController.listAllProducts());
    }//GEN-LAST:event_btn_PanelListProductsActionPerformed

    private void btn_updateTableActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_updateTableActionPerformed
        // TODO add your handling code here:
        if (checkStatus()) {
            String minAux = ftf_minPrice.getText().replace(",", ".");
            String maxAux = ftf_maxPrice.getText().replace(",", ".");

            myListTableRange.setModel(MainController.listAllProductsInRange(Float.parseFloat(minAux), Float.parseFloat(maxAux)));
        }
    }//GEN-LAST:event_btn_updateTableActionPerformed

    private void btn_PanelListRangeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_PanelListRangeActionPerformed
        // TODO add your handling code here:
        panel_AddProduct.setVisible(false);
        panel_ListProducts.setVisible(false);
        panel_RemoveProduct.setVisible(false);
        panel_UpdatePrice.setVisible(false);
        panel_ListProductRange.setVisible(true);
        gatherTF(panel_ListProductRange);
    }//GEN-LAST:event_btn_PanelListRangeActionPerformed

    
    
    public boolean checkStatus() {
        boolean ready = true;

        for (JTextField tf : myFields) {
            if (tf.getText().equals("")) {
                ready = false;
                tf.setBorder(new LineBorder(Color.red));
            } else {
                tf.setBorder(new LineBorder(Color.blue));
            }
        }

        return ready;
    }

    private void gatherTF(Container myContainer) {
        for (Component component : myContainer.getComponents()) {
            if (component instanceof JTextField) {
                myFields.add((JTextField) component);
            }
        }
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainView().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_ActionAddProduct;
    private javax.swing.JButton btn_ActionRemoveProduct;
    private javax.swing.JButton btn_ActionUpdateProduct;
    private javax.swing.JButton btn_PanelAddProduct;
    private javax.swing.JButton btn_PanelListProducts;
    private javax.swing.JButton btn_PanelListRange;
    private javax.swing.JButton btn_PanelRemoveProduct;
    private javax.swing.JButton btn_PanelUpdateProduct;
    private javax.swing.JButton btn_updateTable;
    private javax.swing.JComboBox<String> cb_Category;
    private javax.swing.JPanel contenedor;
    private javax.swing.JFormattedTextField ftf_maxPrice;
    private javax.swing.JFormattedTextField ftf_minPrice;
    private javax.swing.JFormattedTextField ftf_priceAdd;
    private javax.swing.JFormattedTextField ftf_priceUpdate;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JLabel lb_deleteConfirmed;
    private javax.swing.JLabel lb_statusAdd;
    private javax.swing.JLabel lb_updateConfirmed;
    private javax.swing.JTable myListTable;
    private javax.swing.JTable myListTableRange;
    private javax.swing.JPanel panel_AddProduct;
    private javax.swing.JPanel panel_ListProductRange;
    private javax.swing.JPanel panel_ListProducts;
    private javax.swing.JPanel panel_RemoveProduct;
    private javax.swing.JPanel panel_UpdatePrice;
    private javax.swing.JTextField tf_name;
    private javax.swing.JTextField tf_nameRemove;
    private javax.swing.JTextField tf_nameUpdate;
    // End of variables declaration//GEN-END:variables
}
